version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Exponemos el puerto para fuera de Docker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:9092,EXTERNAL://98.83.151.5:9092  # Nombre de host dentro de Docker y fuera de Docker
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT,EXTERNAL
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      KAFKA_LISTENER_PORT_EXTERNAL: 9092
      KAFKA_LISTENER_PROTOCOL_EXTERNAL: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: PLAINTEXT,EXTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092  # Kafka dentro de Docker
      KAFKA_BROKER_EXTERNAL: 98.83.151.5:9092  # Kafka fuera de Docker, conecta usando la IP de la instancia AWS
