version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Expone el puerto para conexiones externas
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://98.83.151.5:9092  # Usar IP externa para conexiones
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENER_PORTS: 9092
      KAFKA_LISTENER_INTERFACE: 0.0.0.0
      KAFKA_LISTENER_INTERNAL: INSIDE://kafka:9092
      KAFKA_LISTENER_EXTERNAL: OUTSIDE://98.83.151.5:9092
      KAFKA_ADVERTISED_LISTENER: OUTSIDE://98.83.151.5:9092  # Dirección pública para conexiones externas

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
