version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092  # Kafka dentro de Docker
      KAFKA_BROKER_EXTERNAL: 98.83.151.5:9092  # Kafka fuera de Docker, conecta usando la IP de la instancia AWS
volumes:
  - ./kafka_data:/var/lib/kafka/data
  - ./zookeeper_data:/var/lib/zookeeper/data
